### ISSUE TITLE
dandiset validation status bar is not "React"ive to changes in the value

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1098] opened 2022-05-11 18:35 UTC
Observed while reviewing/trying https://github.com/dandi/dandi-archive/pull/1097/files . Apparently change in `v-if="currentDandiset.status === 'Pending'"` evaluation doesn't trigger refresh/rerendering of the validation status.   I have no clue in vue to suggest a fix, but I guess it might even be more wide-spread design "issue" that UI is not React'ive in other aspects as well ?  not sure if it should generally be, but here and other spots which rely on outofband actions like it should since users might wait for status to change.

**Comment by waxlamp** [comment] 2022-07-06 22:18
The problem here is that `currentDandiset` refers to an object in the store, so changes to its field values (in this case, `status`) indeed will not trigger the reactive machinery of Vue.

@AlmightyYakob, what are some ways we could resolve this? Probably by tracking `currentDandiset` through a value created with `reactive()` rather than direct-vuex?

More generally, as part of keeping the Vue code up to modern standards, we may want to consider replacing our store infrastructure with [Pinia](https://pinia.vuejs.org/). It would be a big change, but it would solve problems like this one and allow for a more modern, idiomatic expression of store concepts. Thoughts?

**Comment by waxlamp** [comment] 2022-07-13 20:23
> > @AlmightyYakob, what are some ways we could resolve this? Probably by tracking `currentDandiset` through a value created with `reactive()` rather than direct-vuex?
> 
> I'm not sure exactly, it would depend on the intricacies of how vue's `reactive` works with `direct-vuex`, as well as the fact that we're using the vue2 composition-api plugin, so `reactive` would either directly modify the store object, or modify some intermediate representation of it, which might not be allowed. We'd need to investigate.
> 

I was more thinking that we could keep this one value outside the direct-vuex store, and the computed prop in the affected component could reference it directly, instead of going through the store. Would that be feasible (if a bit ugly)?

A better solution would be to use Pinia, but obviously there's a wide gulf in the weight of those two solutions.

> > More generally, as part of keeping the Vue code up to modern standards, we may want to consider replacing our store infrastructure with [Pinia](https://pinia.vuejs.org/). It would be a big change, but it would solve problems like this one and allow for a more modern, idiomatic expression of store concepts. Thoughts?
> 
> 100% support the adoption of Pinia.

Great. We'll need to evaluate what it would take to do so along with the proposed shift to Naruto (#1189).

**Comment by waxlamp** [comment] 2022-09-23 15:58
Ok, we have actually moved to Pinia since the last comment! I confirmed with a test that this is no longer an issue.

I'll close this because the immediate issue is no longer relevant. Please file something new if you discover new instances of the bad behavior.

**Closed by waxlamp** 2022-09-23 15:58 UTC
Labels: bug, UX
