### ISSUE TITLE
bad doi inserted into dandiset metadata

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1702] opened 2023-10-11 02:45 UTC
there are several dandisets, including a couple of published ones that have a doi field in the metadata: `"doi": "10.80507/dandi.123456/0.123456.1234"`

this should never happen. something is inserting this or not removing the "doi" field for a draft dandiset.

**Comment by satra** [comment] 2023-10-11 02:46
see associated issue in https://github.com/dandi/dandi-schema/issues/166

**Comment by waxlamp** [comment] 2023-10-11 13:15
> this should never happen.

Agreed. Marking this as "major" and looking into it.

> something is inserting this or not removing the "doi" field for a draft dandiset.

This is happening due to a chicken-and-egg problem in our validation model that we need to address: namely, we cannot validate the about-to-be-published dandiset without putting a valid(atable) DOI in its metadata, but we don't want to hit the DOI server for a real DOI without first validating our dandiset. So we break the cycle by injecting that obviously fake (but "valid") DOI into the dandiset metadata, then validating, and _then_ obtaining a real DOI. If the real DOI cannot be obtained (due to transient failure of the DOI service, or other issues like dandi/dandi-schema#166) then we wind up publishing an essentially incomplete dandiset featuring that sentinel DOI.

We are looking into what to do about this in the short term, and we're also going to think about longer term solutions to address the root cause.

**Closed** 2023-10-16 14:07 UTC
Labels: bug
