### ISSUE TITLE
Version in production release is a "tag off"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1858] opened 2024-02-06 22:50 UTC
we got it fixed almost fully -- thanks @waxlamp -- but can be seen that `git describe` is off by that actual release tag
 
![image](https://github.com/dandi/dandi-archive/assets/39889/b5f54dfb-74c8-4577-a7f0-6868c48dc974)

my guess is that it might be happen due to "race" between github release done by `auto` and which triggers the backend-production-deploy.yml :

```
on:
  release:
    types: [released]
```

and auto pushing the tag only later in it invocation within release.yml ... so may be smth like

```diff
diff --git a/.github/workflows/backend-production-deploy.yml b/.github/workflows/backend-production-deploy.yml
index e54d99fd..f0f3396b 100644
--- a/.github/workflows/backend-production-deploy.yml
+++ b/.github/workflows/backend-production-deploy.yml
@@ -16,6 +16,9 @@ jobs:
     name: Update release branch
     runs-on: ubuntu-latest
     steps:
+      - name: Sleep a little for a tag to come
+        run: sleep 60
+
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0 # fetch history for all branches and tags
```

could help?

WDYT @jwodder -- is my analysis above for a possible explanation feasible?

**Comment by jwodder** [comment] 2024-02-06 23:33
@yarikoptic The creation of a GitHub release necessarily involves a tag being either created or already present.  I don't see how such a race condition could occur here.

**Comment by waxlamp** [comment] 2024-02-07 01:31
@mvandenburgh and I did get very close, but we'll need to look into this a bit more. This is a dupe of the original issue, so closing in favor of #1089.

**Closed by waxlamp** 2024-02-07 01:31 UTC
