### ISSUE TITLE
Unable to edit contributor names in Dandiset Metadata form

### ISSUE THREAD

**Issue by weiglszonja** [dandi/dandi-archive#2090] opened 2024-12-05 15:12 UTC
When modifying existing contributors in the Metadata form, contributor names are no longer editable. The name field is read-only and can only be removed, not modified.

<img width="400" alt="Screenshot 2024-12-05 at 16 03 54 (2)" src="https://github.com/user-attachments/assets/bbb9f9eb-eca1-4e1a-96a1-35fe9c58ea80">

I think it used to be copyable, which is convenient when the same contributor has to be added to more than one dandiset.

Let me know if this issue should be opened elsewhere.

**Comment by kabilar** [comment] 2024-12-05 15:57
Hi @weiglszonja, thanks for the report.  I am not able to reproduce this error, but maybe its because I have admin privileges. I was able to use the Metadata form to edit contributors:

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/32e1822c-2ed9-4c77-903c-aab085800df1">
  
Which Dandiset are you working with?

**Comment by weiglszonja** [comment] 2024-12-05 16:29
Hmm, maybe this is related to editing an embargoed dataset? (e.g. [this](https://dandiarchive.org/dandiset/001264/draft) or [this](https://dandiarchive.org/dandiset/001265/draft))

**Comment by kabilar** [comment] 2024-12-06 04:38
Thanks.  I will discuss with the team and get back to you.

**Comment by waxlamp** [comment] 2024-12-10 20:40
Hi @weiglszonja! After looking into this, we believe the behavior is as intended--even though it seems to be a poor user experience.

The problem has to do with how the UI for this item is generated from the underlying data specification. Unfortunately, when you click on the field to, e.g., copy it, the way the panel of example names pops up prevents that interaction. Furthermore, as you describe, the only way to edit a name is to delete the field and start fresh.

The best I can do at the moment is suggest that you keep repeated names in a separate application and copy it from there.

We have some ideas about how to fix this. I am going to close this issue in favor of https://github.com/dandi/dandi-schema/issues/270, in case you want to watch for progress there. Sorry I don't have a better solution for you at the current moment.

**Closed by waxlamp** 2024-12-10 20:40 UTC

**Comment by waxlamp** [comment] 2025-01-22 16:53
@weiglszonja, happy new year!

I believe we have remedied the problem you were having in this issue report. Could you please go to the metadata editor for one of your Dandisets and see whether the experience of editing contributor names has indeed improved?
