### ISSUE TITLE
`ingest_zarr_archive` task causes heroku memory errors

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#1181] opened 2022-07-11 20:21 UTC
[The ingest_zarr_archive task](https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/tasks/zarr.py#L147) exceeds the memory quota of 512MB on heroku when running on large datasets like dandiset 108. 

The worker dyno in question, [`checksum-worker`](https://github.com/dandi/dandi-archive/blob/master/Procfile#L11), is responsible for running two tasks - `calculate_sha256` and `ingest_zarr_archive`. Some memory issues with `calculate_sha256` were previously fixed in #1139. Today I ran `ingest_zarr_archive` on dandiset 108, and observed high memory usage (>512 MB, currently using 523 MB about 2 1/2 hours after starting the ingest) when `ingest_zarr_archive` was the only task running on the worker, which implies there are memory issues in that task as well.

**Comment by danlamanna** [comment] 2022-07-11 23:09
It looks like there's S3 errors happening, which is unsurprising given how unreliable networks are when hammering them with requests. We should configure boto3 retries to retry (and backoff) a bit more - https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#configuring-a-retry-mode.

Before this can be done globally, boto3 calls should be moved out of endpoints where possible.

**Comment by danlamanna** [comment] 2022-08-01 19:41
This is effectively a dupe of #1205. The error messages were caused because the worker requires > 512MB ram.

**Closed by danlamanna** 2022-08-01 19:41 UTC
Labels: bug

**Comment by yarikoptic** [comment] 2022-08-01 19:57
>  The error messages were caused because the worker requires > 512MB ram.

But why does it require that much???
