### ISSUE TITLE
Test DOIs are being saved to draft version metadata

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#1556] opened 2023-04-03 19:08 UTC
A bug is causing test DOIs to get saved to draft versions' metadata ([example](https://api.dandiarchive.org/api/dandisets/000409/versions/draft/info/), not the `doi` field in the metadata object).

A possible cause for this is the fact that we inject "dummy" DOIs into draft version metadata for validation purposes ([here](https://github.com/dandi/dandi-archive/blob/83d3a10432f6554969542a2f8fc209bc5f9c269f/dandiapi/api/services/publish/__init__.py#L170-L171) for example).

**Comment by waxlamp** [comment] 2024-02-02 21:23
This is a dupe of #1709 (if not, please re-open, @mvandenburgh).

**Closed by waxlamp** 2024-02-02 21:23 UTC
Labels: bug
