### ISSUE TITLE
Zarr 2a613dd6-73c7-45f7-9b17-eae495c26277 manifest is out of sync with S3

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#1378] opened 2022-11-22 16:29 UTC
Various entries were recently deleted from Zarr 2a613dd6-73c7-45f7-9b17-eae495c26277, yet the Archive's API still reports them as part of the Zarr.

Specifically, running the following script:

```python
from dandi.dandiapi import DandiAPIClient, RemoteZarrEntry
import boto3
from botocore import UNSIGNED
from botocore.client import Config
import sys

s3bucket = "dandiarchive"
zarr_id = sys.argv[1]
s3prefix = f"zarr/{zarr_id}/"

with DandiAPIClient.for_dandi_instance("dandi") as client:
    root = RemoteZarrEntry(client=client, zarr_id=zarr_id, parts=(), _known_dir=True)
    entries = {str(e): e.get_digest().value for e in root.iterfiles()}
print("Found", len(entries), "entries in Zarr on Archive")

s3 = boto3.client("s3", config=Config(signature_version=UNSIGNED))
for page in s3.get_paginator("list_objects_v2").paginate(Bucket=s3bucket, Prefix=s3prefix):
    for obj in page["Contents"]:
        path = obj["Key"][len(s3prefix):]
        digest = obj["ETag"].strip('"')
        if path not in entries:
            print(f"Path {path} is only in S3")
        elif entries[path] != digest:
            print(f"Digest mismatch for {path}: Archive says {entries[path]}, S3 says {digest}")
        entries.pop(path, None)

for e in entries:
    print(f"Path {e} is only on Archive")
```

outputs the following:

```
Found 37230 entries in Zarr on Archive
Path 0/0/0/15/12/105 is only on Archive
Path 0/0/0/15/12/116 is only on Archive
Path 0/0/0/15/12/124 is only on Archive
Path 0/0/0/15/12/137 is only on Archive
Path 0/0/0/15/12/140 is only on Archive
Path 0/0/0/15/12/161 is only on Archive
Path 0/0/0/15/12/172 is only on Archive
Path 0/0/0/15/12/178 is only on Archive
Path 0/0/0/15/12/185 is only on Archive
Path 0/0/0/15/12/19 is only on Archive
Path 0/0/0/15/12/196 is only on Archive
Path 0/0/0/15/12/206 is only on Archive
Path 0/0/0/15/12/21 is only on Archive
Path 0/0/0/15/12/215 is only on Archive
Path 0/0/0/15/12/227 is only on Archive
Path 0/0/0/15/12/234 is only on Archive
Path 0/0/0/15/12/32 is only on Archive
Path 0/0/0/15/12/38 is only on Archive
Path 0/0/0/15/12/45 is only on Archive
Path 0/0/0/15/12/64 is only on Archive
Path 0/0/0/15/12/77 is only on Archive
Path 0/0/0/15/12/80 is only on Archive
Path 0/0/0/15/12/93 is only on Archive
Path 0/0/0/15/12/99 is only on Archive
Path 0/0/0/15/4/100 is only on Archive
Path 0/0/0/15/4/101 is only on Archive
Path 0/0/0/15/4/102 is only on Archive
Path 0/0/0/15/4/103 is only on Archive
Path 0/0/0/15/4/104 is only on Archive
Path 0/0/0/15/4/105 is only on Archive
Path 0/0/0/15/4/106 is only on Archive
Path 0/0/0/15/4/107 is only on Archive
Path 0/0/0/15/4/108 is only on Archive
Path 0/0/0/15/4/109 is only on Archive
Path 0/0/0/15/4/110 is only on Archive
Path 0/0/0/15/4/111 is only on Archive
Path 0/0/0/15/4/112 is only on Archive
Path 0/0/0/15/4/113 is only on Archive
Path 0/0/0/15/4/114 is only on Archive
Path 0/0/0/15/4/115 is only on Archive
Path 0/0/0/15/4/116 is only on Archive
Path 0/0/0/15/4/117 is only on Archive
Path 0/0/0/15/4/118 is only on Archive
Path 0/0/0/15/4/119 is only on Archive
Path 0/0/0/15/4/120 is only on Archive
Path 0/0/0/15/4/121 is only on Archive
Path 0/0/0/15/4/122 is only on Archive
Path 0/0/0/15/4/123 is only on Archive
Path 0/0/0/15/4/124 is only on Archive
Path 0/0/0/15/4/125 is only on Archive
Path 0/0/0/15/4/126 is only on Archive
Path 0/0/0/15/4/127 is only on Archive
Path 0/0/0/15/4/128 is only on Archive
Path 0/0/0/15/4/129 is only on Archive
Path 0/0/0/15/4/130 is only on Archive
Path 0/0/0/15/4/131 is only on Archive
Path 0/0/0/15/4/132 is only on Archive
Path 0/0/0/15/4/133 is only on Archive
Path 0/0/0/15/4/134 is only on Archive
Path 0/0/0/15/4/135 is only on Archive
Path 0/0/0/15/4/136 is only on Archive
Path 0/0/0/15/4/137 is only on Archive
Path 0/0/0/15/4/138 is only on Archive
Path 0/0/0/15/4/139 is only on Archive
Path 0/0/0/15/4/14 is only on Archive
Path 0/0/0/15/4/140 is only on Archive
Path 0/0/0/15/4/141 is only on Archive
Path 0/0/0/15/4/142 is only on Archive
Path 0/0/0/15/4/143 is only on Archive
Path 0/0/0/15/4/144 is only on Archive
Path 0/0/0/15/4/145 is only on Archive
Path 0/0/0/15/4/146 is only on Archive
Path 0/0/0/15/4/147 is only on Archive
Path 0/0/0/15/4/148 is only on Archive
Path 0/0/0/15/4/149 is only on Archive
Path 0/0/0/15/4/15 is only on Archive
Path 0/0/0/15/4/150 is only on Archive
Path 0/0/0/15/4/151 is only on Archive
Path 0/0/0/15/4/152 is only on Archive
Path 0/0/0/15/4/153 is only on Archive
Path 0/0/0/15/4/154 is only on Archive
Path 0/0/0/15/4/155 is only on Archive
Path 0/0/0/15/4/156 is only on Archive
Path 0/0/0/15/4/157 is only on Archive
Path 0/0/0/15/4/158 is only on Archive
Path 0/0/0/15/4/159 is only on Archive
Path 0/0/0/15/4/16 is only on Archive
Path 0/0/0/15/4/160 is only on Archive
Path 0/0/0/15/4/161 is only on Archive
Path 0/0/0/15/4/162 is only on Archive
Path 0/0/0/15/4/163 is only on Archive
Path 0/0/0/15/4/164 is only on Archive
Path 0/0/0/15/4/165 is only on Archive
Path 0/0/0/15/4/166 is only on Archive
Path 0/0/0/15/4/167 is only on Archive
Path 0/0/0/15/4/168 is only on Archive
Path 0/0/0/15/4/169 is only on Archive
Path 0/0/0/15/4/17 is only on Archive
Path 0/0/0/15/4/170 is only on Archive
Path 0/0/0/15/4/171 is only on Archive
Path 0/0/0/15/4/172 is only on Archive
Path 0/0/0/15/4/173 is only on Archive
Path 0/0/0/15/4/174 is only on Archive
Path 0/0/0/15/4/175 is only on Archive
Path 0/0/0/15/4/176 is only on Archive
Path 0/0/0/15/4/177 is only on Archive
Path 0/0/0/15/4/178 is only on Archive
Path 0/0/0/15/4/179 is only on Archive
Path 0/0/0/15/4/18 is only on Archive
Path 0/0/0/15/4/180 is only on Archive
Path 0/0/0/15/4/181 is only on Archive
Path 0/0/0/15/4/182 is only on Archive
Path 0/0/0/15/4/183 is only on Archive
Path 0/0/0/15/4/184 is only on Archive
Path 0/0/0/15/4/185 is only on Archive
Path 0/0/0/15/4/186 is only on Archive
Path 0/0/0/15/4/187 is only on Archive
Path 0/0/0/15/4/188 is only on Archive
Path 0/0/0/15/4/189 is only on Archive
Path 0/0/0/15/4/19 is only on Archive
Path 0/0/0/15/4/190 is only on Archive
Path 0/0/0/15/4/191 is only on Archive
Path 0/0/0/15/4/192 is only on Archive
Path 0/0/0/15/4/193 is only on Archive
Path 0/0/0/15/4/194 is only on Archive
Path 0/0/0/15/4/195 is only on Archive
Path 0/0/0/15/4/196 is only on Archive
Path 0/0/0/15/4/197 is only on Archive
Path 0/0/0/15/4/198 is only on Archive
Path 0/0/0/15/4/199 is only on Archive
Path 0/0/0/15/4/20 is only on Archive
Path 0/0/0/15/4/200 is only on Archive
Path 0/0/0/15/4/201 is only on Archive
Path 0/0/0/15/4/202 is only on Archive
Path 0/0/0/15/4/203 is only on Archive
Path 0/0/0/15/4/204 is only on Archive
Path 0/0/0/15/4/205 is only on Archive
Path 0/0/0/15/4/206 is only on Archive
Path 0/0/0/15/4/207 is only on Archive
Path 0/0/0/15/4/208 is only on Archive
Path 0/0/0/15/4/209 is only on Archive
Path 0/0/0/15/4/21 is only on Archive
Path 0/0/0/15/4/210 is only on Archive
Path 0/0/0/15/4/211 is only on Archive
Path 0/0/0/15/4/212 is only on Archive
Path 0/0/0/15/4/213 is only on Archive
Path 0/0/0/15/4/214 is only on Archive
Path 0/0/0/15/4/215 is only on Archive
Path 0/0/0/15/4/216 is only on Archive
Path 0/0/0/15/4/217 is only on Archive
Path 0/0/0/15/4/218 is only on Archive
Path 0/0/0/15/4/219 is only on Archive
Path 0/0/0/15/4/22 is only on Archive
Path 0/0/0/15/4/220 is only on Archive
Path 0/0/0/15/4/221 is only on Archive
Path 0/0/0/15/4/222 is only on Archive
Path 0/0/0/15/4/223 is only on Archive
Path 0/0/0/15/4/224 is only on Archive
Path 0/0/0/15/4/225 is only on Archive
Path 0/0/0/15/4/226 is only on Archive
Path 0/0/0/15/4/227 is only on Archive
Path 0/0/0/15/4/228 is only on Archive
Path 0/0/0/15/4/229 is only on Archive
Path 0/0/0/15/4/23 is only on Archive
Path 0/0/0/15/4/230 is only on Archive
Path 0/0/0/15/4/231 is only on Archive
Path 0/0/0/15/4/232 is only on Archive
Path 0/0/0/15/4/233 is only on Archive
Path 0/0/0/15/4/234 is only on Archive
Path 0/0/0/15/4/235 is only on Archive
Path 0/0/0/15/4/236 is only on Archive
Path 0/0/0/15/4/237 is only on Archive
Path 0/0/0/15/4/238 is only on Archive
Path 0/0/0/15/4/239 is only on Archive
Path 0/0/0/15/4/24 is only on Archive
Path 0/0/0/15/4/25 is only on Archive
Path 0/0/0/15/4/26 is only on Archive
Path 0/0/0/15/4/27 is only on Archive
Path 0/0/0/15/4/28 is only on Archive
Path 0/0/0/15/4/29 is only on Archive
Path 0/0/0/15/4/30 is only on Archive
Path 0/0/0/15/4/31 is only on Archive
Path 0/0/0/15/4/32 is only on Archive
Path 0/0/0/15/4/33 is only on Archive
Path 0/0/0/15/4/34 is only on Archive
Path 0/0/0/15/4/35 is only on Archive
Path 0/0/0/15/4/36 is only on Archive
Path 0/0/0/15/4/37 is only on Archive
Path 0/0/0/15/4/38 is only on Archive
Path 0/0/0/15/4/39 is only on Archive
Path 0/0/0/15/4/40 is only on Archive
Path 0/0/0/15/4/41 is only on Archive
Path 0/0/0/15/4/42 is only on Archive
Path 0/0/0/15/4/43 is only on Archive
Path 0/0/0/15/4/44 is only on Archive
Path 0/0/0/15/4/45 is only on Archive
Path 0/0/0/15/4/46 is only on Archive
Path 0/0/0/15/4/47 is only on Archive
Path 0/0/0/15/4/48 is only on Archive
Path 0/0/0/15/4/49 is only on Archive
Path 0/0/0/15/4/50 is only on Archive
Path 0/0/0/15/4/51 is only on Archive
Path 0/0/0/15/4/52 is only on Archive
Path 0/0/0/15/4/53 is only on Archive
Path 0/0/0/15/4/54 is only on Archive
Path 0/0/0/15/4/55 is only on Archive
Path 0/0/0/15/4/56 is only on Archive
Path 0/0/0/15/4/57 is only on Archive
Path 0/0/0/15/4/58 is only on Archive
Path 0/0/0/15/4/59 is only on Archive
Path 0/0/0/15/4/60 is only on Archive
Path 0/0/0/15/4/61 is only on Archive
Path 0/0/0/15/4/62 is only on Archive
Path 0/0/0/15/4/63 is only on Archive
Path 0/0/0/15/4/64 is only on Archive
Path 0/0/0/15/4/65 is only on Archive
Path 0/0/0/15/4/66 is only on Archive
Path 0/0/0/15/4/67 is only on Archive
Path 0/0/0/15/4/68 is only on Archive
Path 0/0/0/15/4/69 is only on Archive
Path 0/0/0/15/4/70 is only on Archive
Path 0/0/0/15/4/71 is only on Archive
Path 0/0/0/15/4/72 is only on Archive
Path 0/0/0/15/4/73 is only on Archive
Path 0/0/0/15/4/74 is only on Archive
Path 0/0/0/15/4/75 is only on Archive
Path 0/0/0/15/4/76 is only on Archive
Path 0/0/0/15/4/77 is only on Archive
Path 0/0/0/15/4/78 is only on Archive
Path 0/0/0/15/4/79 is only on Archive
Path 0/0/0/15/4/80 is only on Archive
Path 0/0/0/15/4/81 is only on Archive
Path 0/0/0/15/4/82 is only on Archive
Path 0/0/0/15/4/83 is only on Archive
Path 0/0/0/15/4/84 is only on Archive
Path 0/0/0/15/4/85 is only on Archive
Path 0/0/0/15/4/86 is only on Archive
Path 0/0/0/15/4/87 is only on Archive
Path 0/0/0/15/4/88 is only on Archive
Path 0/0/0/15/4/89 is only on Archive
Path 0/0/0/15/4/90 is only on Archive
Path 0/0/0/15/4/91 is only on Archive
Path 0/0/0/15/4/92 is only on Archive
Path 0/0/0/15/4/93 is only on Archive
Path 0/0/0/15/4/94 is only on Archive
Path 0/0/0/15/4/95 is only on Archive
Path 0/0/0/15/4/96 is only on Archive
Path 0/0/0/15/4/97 is only on Archive
Path 0/0/0/15/4/98 is only on Archive
Path 0/0/0/15/4/99 is only on Archive
Path 0/0/0/15/9/105 is only on Archive
Path 0/0/0/15/9/172 is only on Archive
Path 0/0/0/15/9/178 is only on Archive
Path 0/0/0/15/9/196 is only on Archive
Path 0/0/0/15/9/92 is only on Archive
```

**Comment by yarikoptic** [comment] 2022-11-28 17:14
ping @waxlamp . Please prioritize this issue to be troublshooted at and resolved -- IIRC papertrail has only limited in duration archive of logs which might be necessary for proper investigation to solve the original bug leading to this situation.

FWIW, I've reran the script of @jwodder  and confirmed that the issue persists:

```
❯ python bad_zarr_1378.py 2a613dd6-73c7-45f7-9b17-eae495c26277
Found 37230 entries in Zarr on Archive
Path 0/0/0/15/12/105 is only on Archive
...
```

**Comment by waxlamp** [comment] 2022-11-28 21:01
Do we know how those files were deleted from the database? Looking at the dandi CLI source, there are only two places where Zarr files are deleted from the server ([here](https://github.com/dandi/dandi-cli/blob/master/dandi/files/zarr.py#L429) and [here](https://github.com/dandi/dandi-cli/blob/master/dandi/files/zarr.py#L503)), and both take place during upload (to remove old files that are not in the local Zarr, I think).

Questions:
1. Am I missing other places where Zarr chunks are deleted?
2. Do we know which method attempted to delete files in this case?
2a. Can we create a repro that leaves files undeleted on S3 but deleted in the Django database?

**Comment by satra** [comment] 2022-11-28 22:25
@waxlamp - if i understand the issue correctly, the files are deleted in s3, but still are listed via the API on the server side as part of the specific zarr object, which is the flip of how you are interpreting it.

**Comment by yarikoptic** [comment] 2022-11-28 23:38
@waxlamp I am with @satra on interpretation of the situation although may be it could be that may be they were populated in the archive.  It could potentially be (depending on how dandi-archive implemented it) that server got listing but never got files uploaded to S3, but that is unlikely the case since that file did existon S3:

```
❯ datalad ls -aL s3://dandiarchive/zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/0/0/0/15/12/105
Connecting to bucket: dandiarchive
[INFO   ] S3 session: Connecting to the bucket dandiarchive anonymously 
Bucket info:
  Versioning: {'Versioning': 'Enabled'}
     Website: dandiarchive.s3-website-us-east-1.amazonaws.com
         ACL: <Policy: None (owner) = FULL_CONTROL>
zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/0/0/0/15/12/105 2022-11-17T15:19:33.000Z DeleteMarker
zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/0/0/0/15/12/105 2022-06-30T13:39:05.000Z 1643037 ver:s.S7LmmxybTJouTRGR5VexheLFGBZpMc  acl:S3ResponseError: 404 Not Found
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/0/0/0/15/12/105</Key><RequestId>0FDJZCQYEZT3D6D5</RequestId><HostId>vHCokxNdO0MiyawywMJ6HNTs9CGQhsrRkzgwK/th+q+bUwn6S4DCQAWWSeEaf/Jiw9TArkZFzaU=</HostId></Error>  http://dandiarchive.s3.amazonaws.com/zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/0/0/0/15/12/105?versionId=s.S7LmmxybTJouTRGR5VexheLFGBZpMc [OK]
```

> Do we know how those files were deleted from the database? 

in all likeness - through an API call to `zarr_delete_files`.  Indeed it is most likely that end point was triggered by dandi-cli in one of the locations you pointed out. But do we have logs for the API call?

Besides all the GET calls, I got only two other calls logged in heroku logs

```
(base) dandi@drogon:/mnt/backup/dandi/heroku-logs/dandi-api$ grep -v GET /tmp/2a613dd6-73c7-45f7-9b17-eae495c26277.logs
20221117-1001.log:2022-11-17T15:19:23.947635+00:00 app[web.1]: 10.1.8.154 - - [17/Nov/2022:15:19:23 +0000] "DELETE /api/zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/upload/ HTTP/1.1" 204 0 "-" "dandi/0.46.6 requests/2.25.1 CPython/3.8.10"
20221117-1001.log:2022-11-17T15:19:23.944511+00:00 heroku[router]: at=info method=DELETE path="/api/zarr/2a613dd6-73c7-45f7-9b17-eae495c26277/upload/" host=api.dandiarchive.org request_id=a32bcaad-7ac4-4a8f-83f3-416c78f41121 fwd="18.18.93.11" dyno=web.1 connect=0ms service=55ms status=204 bytes=352 protocol=https
```

so there was a deleted upload. So may be some files were uploaded to S3 but then upload DELETED.

> Looking at the dandi CLI source, there are only two places where Zarr files are deleted from the server ([here](https://github.com/dandi/dandi-cli/blob/master/dandi/files/zarr.py#L429) and [here](https://github.com/dandi/dandi-cli/blob/master/dandi/files/zarr.py#L503)), and both take place during upload (to remove old files that are not in the local Zarr, I think).

the former https://github.com/dandi/dandi-cli/blob/master/dandi/files/zarr.py#L429 is the likely one which was used, the latter one is to remove entire zarr, which isn't the case here.

> 2. Do we know which method attempted to delete files in this case?
>     2a. Can we create a repro that leaves files undeleted on S3 but deleted in the Django database?

As @satra pointed out - we have the inverse situation. Files are deleted on S3 but remain "known" to dandi-archive.   If we are to ask questions:
- At what stage they become known to dandi-archive?
- what happens when DELETE endpoint is called -- ie how does it interact with possibly new upload? 
- what happens when upload is DELETED (which seems what happened for this zarr at least once some time)?

**Comment by jwodder** [comment] 2022-11-28 23:41
@yarikoptic The latter link to the CLI source does not remove the entire Zarr; it removes from a previously-uploaded Zarr (to which we are uploading again) any entries that were deleted locally since the last upload.  I suspect that this was the spot that was used, and then something went wrong with the ingestion.

**Comment by AlmightyYakob** [comment] 2022-11-29 00:29
I looked into this a bit, and it seems the following statements are true:

1. When deleting a path from a zarr file (`DELETE zarr/{zarr_id}/files`), any corresponding checksum files are **not** deleted.
2. When the `/zarr/{zarr_id}.zarr/{path}` endpoint is called, it uses the **checksum files** to list the contents of a given directory. 


So it seems that based on the timeline of events, this would explain why the API still reports missing files. The reason that the subsequent ingestion didn't fix this is that the ingestion script only looks at what is currently in the S3 zarr prefix, not the checksums at all, and so never comes across those no longer existent directories.

The direct fix would be to delete any necessary checksum files when an inner-zarr file is deleted, however this is a little more complex than it seems, since there are a lot of edge cases / semantics when it comes to determining if a particular zarr checksum file can/can't be deleted.


So there's two possible approaches right now.

1. We implement the fix, and this issue remains open until that fix is merged and deployed (however long that takes).
2. We fix this specific zarr directly and close this issue, while the general fix is being worked on.

Which seems like a better approach?

**Comment by yarikoptic** [comment] 2022-11-29 03:33
- There is no guarantee that it is only this Zarr which needs fixing, but I am ok to get it fixed first and have another dedicated issue opened.
- "However long" sounds too non specific, there can't be some sensible ETA?
- Does forced re-ingestion regenerate checksum files?

**Comment by yarikoptic** [comment] 2022-11-29 03:34
Oh, and thank you @AlmightyYakob for digging to the bottom of it.

**Comment by satra** [comment] 2022-11-29 03:41
@yarikoptic and @AlmightyYakob - it may be worth discussing what purpose the api service for checksum tree is serving and whether simply querying s3 directly could be something the CLI could use. since s3 would have etag, whether doing an s3 listobjects on any prefix/hence subtree, especially since this can be a high throughput s3 api operation could provide faster and more clean access to state of zarr. 

caveat: i don't know how this will work for zarrbargo, but that hasn't been implemented yet as far as i know.

**Comment by AlmightyYakob** [comment] 2022-11-29 19:07
> @yarikoptic and @AlmightyYakob - it may be worth discussing what purpose the api service for checksum tree is serving and whether simply querying s3 directly could be something the CLI could use. since s3 would have etag, whether doing an s3 listobjects on any prefix/hence subtree, especially since this can be a high throughput s3 api operation could provide faster and more clean access to state of zarr.

I did want clarity on this, what is the intended purpose of the zarr paths endpoint? What is it ultimately being used for? @yarikoptic @jwodder 

> caveat: i don't know how this will work for zarrbargo, but that hasn't been implemented yet as far as i know.

Correct, it's not implemented.

**Comment by jwodder** [comment] 2022-11-29 19:20
@AlmightyYakob At the moment, I believe the `/zarr/{zarr_id}.zarr/{path}` endpoint is only used by the client to get the current entries in a Zarr so it knows what to (re)upload or download.

**Comment by AlmightyYakob** [comment] 2022-11-29 19:20
> * There is no guarantee that it is only this Zarr which needs fixing, but I am ok to get it fixed first and have another dedicated issue opened.

:+1: 

> * "However long" sounds too non specific, there can't be some sensible ETA?

As I said, a thorough fix could be complex, and we might want to evaluate several options. I don't expect it to take any unprecedented amount of time, but I'm just not sure. Maybe a week, or two if there are issues. The secondary obstacle is writing a script to identify any additional zarrs where this may be the case, and fix them.

> * Does forced re-ingestion regenerate checksum files?

The problem is that zarr ingestion currently only looks at the source files in s3, and so if the files that are deleted are "alone" in a subtree, that subtree won't show up at all in the s3 object listing.

**Comment by AlmightyYakob** [comment] 2022-11-29 19:22
> @AlmightyYakob At the moment, I believe the `/zarr/{zarr_id}.zarr/{path}` endpoint is only used by the client to get the current entries in a Zarr so it knows what to (re)upload or download.

Okay, that makes sense. Is a hierarchical view (the current design) desired for this? Or is a flat (paginated) listing just as easy?

**Comment by jwodder** [comment] 2022-11-29 19:25
@AlmightyYakob From the client's perspective, a paginated view would be better, as it would likely mean fewer requests to get everything.  Switching over would mean losing some functionality around being able to list individual directories within Zarrs, but I don't think that's actually needed for anything.

**Comment by yarikoptic** [comment] 2022-11-29 20:42
> > * Does forced re-ingestion regenerate checksum files?
> 
> The problem is that zarr ingestion currently only looks at the source files in s3, and so if the files that are deleted are "alone" in a subtree, that subtree won't show up at all in the s3 object listing.

I am sorry, @AlmightyYakob , could you please elaborate a little more -- I do not get what "alone" means in this context especially since S3 doesn't have a notion of "tree" and we just get listing of all keys under specific prefix.   
The point of my question was: wouldn't we list the entire zarr prefix and regenerate entire checksum file for that zarr "from scratch" thus eliminating any entry which is no longer on S3 under that zarr prefix?

**Comment by AlmightyYakob** [comment] 2022-11-29 22:29
> I am sorry, @AlmightyYakob , could you please elaborate a little more -- I do not get what "alone" means in this context especially since S3 doesn't have a notion of "tree" and we just get listing of all keys under specific prefix. The point of my question was: wouldn't we list the entire zarr prefix and regenerate entire checksum file for that zarr "from scratch" thus eliminating any entry which is no longer on S3 under that zarr prefix?

There are two separate locations (prefixes) in the s3 bucket that objects are stored:

* The first is where the actual zarr files are stored, with no extra files or modifications.
* The second is where the checksum files are stored, in a mirrored path structure, with `.checksum` files being placed at every "directory". I know there is no actual directory structure in S3, but the `.checksum` files are placed at each "step" in the object path in order to essentially create/maintain one.

So for example, if the following zarr files existing at the s3 prefix for a specific zarr:
* `0/0/0`
* `0/0/1`
* `0/1/2`

The secondary location would have the following checksum files at the corresponding prefix:
* `.checksum`
* `0/.checksum`
* `0/0/.checksum`
* `0/1/.checksum`


This is done so that the direct zarr file listing isn't tainted with a bunch of `.checksum` files.

---

So going back to what I originally said, and using the example above, if the file `0/1/2` was deleted, when zarr ingestion was run again, the listed files would be

* `0/0/0`
* `0/0/1`

And would not at all contain the `0/1` sub-tree. So the `0/1/.checksum` file would remain there, and would report the `0/1/2` file, even though it's no longer there.

**Comment by yarikoptic** [comment] 2022-11-29 22:43
I see, thank you for the detailed explanation @AlmightyYakob !  So please confirm or dispute me: the bug is in ingestion (or underlying function dumping the hierarchy of `/.checksum` files) which does not care to get the exhaustive list of already present `/.checksum`\s under the zarr checksum prefix first to be able to remove those no longer present upon completion of generation of the set of new `/.checksum` files.  So fix would be "get the list, at the end of populating new `/.checksum` files, remove those which are no longer there".  correct?

**Comment by AlmightyYakob** [comment] 2022-12-06 21:07
@yarikoptic @jwodder The underlying issue has been addressed, and this zarr has been re-ingested. This should now be solved for all zarrs going forward (any zarrs that are ingested now or in the future), but I'll be making another PR in the near future that will address this for all zarrs.

**Closed** 2022-12-06 21:18 UTC
