### ISSUE TITLE
dandiset issues

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1684] opened 2023-09-21 19:27 UTC
Problem: It is hard for users to report problems with dandisets, make requests, and have the dandiset owners respond. The current approach is just with email, but that is not transparent or visible to the broader dandi community.

Proposed solution: I'd like a button on each dandiset landing page that has the label "Issues" and takes the user to the Issues page of the corresponding github repo, e.g. https://github.com/dandisets/000041/issues

Bonus: Use the GitHub API to determine the number of active issues and display it in the button, e.g. "Issues (3)"

**Comment by yarikoptic** [comment] 2023-09-21 21:03
Let's consider a duplicate of #863 and please chime in on https://github.com/dandi/dandi-archive/pull/1595 -- I should get back to it so we finalize and look to implement it.

**Closed by yarikoptic** 2023-09-21 21:03 UTC

**Comment by bendichter** [comment] 2023-09-22 01:21
ah yes, I missed that. Thanks, I commented in support of the PR
